
import React, { useState } from 'react';
import { GeneratedConfig, ConnectionStatus } from '../types';

interface TerminalOutputProps {
  config: GeneratedConfig | null;
  isGenerating: boolean;
  onClear: () => void;
  connectionStatus: ConnectionStatus;
}

const TerminalOutput: React.FC<TerminalOutputProps> = ({ config, isGenerating, onClear, connectionStatus }) => {
  const [activeTab, setActiveTab] = useState<'cli' | 'guide'>('cli');

  const copyToClipboard = () => {
    if (config) {
      navigator.clipboard.writeText(config.cliCommands);
      const btn = document.getElementById('copy-btn');
      if (btn) {
        const originalText = btn.innerHTML;
        btn.innerHTML = '<i class="fas fa-check text-green-400"></i>';
        setTimeout(() => btn.innerHTML = originalText, 2000);
      }
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-700/50 rounded-2xl shadow-2xl h-full flex flex-col overflow-hidden">
      {/* Terminal Header */}
      <div className="bg-slate-950 px-4 py-3 flex items-center justify-between border-b border-slate-800">
        <div className="flex gap-2">
          <div className={`w-3 h-3 rounded-full ${connectionStatus === 'CONNECTED' ? 'bg-green-500' : 'bg-red-500/30'}`}></div>
          <div className="w-3 h-3 rounded-full bg-yellow-500/30"></div>
          <div className="w-3 h-3 rounded-full bg-blue-500/30"></div>
        </div>
        <div className="flex bg-slate-900 rounded-lg p-1">
          <button 
            onClick={() => setActiveTab('cli')}
            className={`px-4 py-1.5 rounded-md text-xs font-bold transition-all ${activeTab === 'cli' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/40' : 'text-slate-500 hover:text-slate-300'}`}
          >
            CLI COMMANDS
          </button>
          <button 
            onClick={() => setActiveTab('guide')}
            className={`px-4 py-1.5 rounded-md text-xs font-bold transition-all ${activeTab === 'guide' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/40' : 'text-slate-500 hover:text-slate-300'}`}
          >
            EXPLANATION
          </button>
        </div>
        <div className="flex items-center gap-3">
          {config && (
            <button 
              onClick={onClear}
              className="text-slate-500 hover:text-red-400 transition-colors text-sm"
              title="Clear current config"
            >
              <i className="fas fa-trash-alt"></i>
            </button>
          )}
          <button 
            id="copy-btn"
            onClick={copyToClipboard}
            className="text-slate-400 hover:text-blue-400 transition-colors"
            title="Copy to clipboard"
          >
            <i className="fas fa-copy"></i>
          </button>
        </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-6 bg-[#0B0E14] custom-scrollbar">
        {isGenerating ? (
          <div className="h-full flex flex-col items-center justify-center space-y-4">
            <div className="w-12 h-12 border-4 border-blue-500/20 border-t-blue-500 rounded-full animate-spin"></div>
            <p className="text-blue-400 font-mono text-sm animate-pulse">Compiling configuration...</p>
          </div>
        ) : config ? (
          activeTab === 'cli' ? (
            <div className="cli-font text-sm">
              <div className="text-slate-500 mb-4 flex justify-between items-center">
                <span>! Cisco Configuration Generated by AI</span>
                <span className="text-[10px] bg-blue-500/10 text-blue-400 px-2 py-0.5 rounded border border-blue-500/20">LINK ACTIVE</span>
              </div>
              <pre className="text-green-400 leading-relaxed whitespace-pre-wrap">{config.cliCommands}</pre>
            </div>
          ) : (
            <div className="space-y-6">
              <section>
                <div className="flex items-center justify-between mb-2">
                  <h4 className="text-blue-400 font-bold text-xs uppercase tracking-widest">Description</h4>
                </div>
                <p className="text-slate-300 text-sm leading-relaxed">{config.explanation}</p>
              </section>
              <section>
                <h4 className="text-orange-400 font-bold text-xs uppercase tracking-widest mb-2">Security Best Practices</h4>
                <ul className="space-y-2">
                  {config.bestPractices.map((bp, i) => (
                    <li key={i} className="flex gap-3 text-sm text-slate-400">
                      <i className="fas fa-check-circle text-orange-500/50 mt-1"></i>
                      <span>{bp}</span>
                    </li>
                  ))}
                </ul>
              </section>
            </div>
          )
        ) : (
          <div className="h-full flex flex-col items-center justify-center text-slate-600 text-center opacity-40">
            {connectionStatus === 'CONNECTED' ? (
              <>
                <i className="fas fa-terminal text-6xl mb-4 text-green-500/50"></i>
                <p className="font-mono text-sm">Thiết bị đã sẵn sàng. Hãy nhập yêu cầu cấu hình.</p>
              </>
            ) : (
              <>
                <i className="fas fa-link-slash text-6xl mb-4 text-red-500/30"></i>
                <p className="font-mono text-sm">Chưa có kết nối. Vui lòng kết nối thiết bị ở Sidebar.</p>
              </>
            )}
          </div>
        )}
      </div>

      {/* Footer Info */}
      <div className="bg-slate-950 px-6 py-3 border-t border-slate-800 flex items-center justify-between text-[10px] text-slate-500 font-mono">
        <div className="flex gap-4">
          <span>ENC: AES-256</span>
          <span className={connectionStatus === 'CONNECTED' ? 'text-green-500' : 'text-red-500'}>
            LINK: {connectionStatus}
          </span>
        </div>
        <div>
          {config ? `LEN: ${config.cliCommands.length} Chars` : 'IDLE'}
        </div>
      </div>
    </div>
  );
};

export default TerminalOutput;
